version: '3.1'

services:
  addressbook-db:
    image: postgres:9.6.13
    environment:
      POSTGRES_PASSWORD: addressbookadmin
      POSTGRES_USER: addressbookadmin
      POSTGRES_DB: addressbookdb
    expose:
      - 5432
    ports:
      - 5008:5432