spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5008/addressbookdb
    username: addressbookadmin
    password: addressbookadmin

server:
  port: 8080

logging:
  level:
    org.springframework: ERROR
    com.cyberexplorer: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: addressbook.log